# Generated by Django 5.2.15 on 2026-06-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('optimization', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('simulation', '仿真报告'), ('optimization', '优化报告'), ('comparison', '对比报告')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='network.network')),
                ('optimization_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='optimization.optimizationresult')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='simulation.simulation')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=50)),
                ('metric_type', models.CharField(choices=[('delay', '延误'), ('queue', '排队长度'), ('throughput', '吞吐量'), ('stops', '停车次数'), ('vcr', '饱和度')], max_length=20)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation_time', models.FloatField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='network.network')),
            ],
            options={
                'verbose_name': '性能指标',
                'verbose_name_plural': '性能指标',
                'ordering': ['-timestamp'],
            },
        ),
    ]
