# Generated by Django 5.2.15 on 2026-06-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('intersection', '单点交叉口'), ('corridor', '干线绿波'), ('network', '区域路网')], max_length=20)),
                ('algorithm', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_params', models.JSONField(default=dict)),
                ('constraints', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '算法配置',
                'verbose_name_plural': '算法配置',
                'unique_together': {('level', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('intersection', '单点交叉口'), ('corridor', '干线绿波'), ('network', '区域路网')], max_length=20)),
                ('algorithm', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('signal_timings', models.JSONField()),
                ('performance', models.JSONField()),
                ('convergence', models.JSONField(blank=True, null=True)),
                ('computation_time', models.FloatField(default=0)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_results', to='network.network')),
            ],
            options={
                'verbose_name': '优化结果',
                'verbose_name_plural': '优化结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
