# Generated by Django 5.2.15 on 2026-06-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('length', models.FloatField()),
                ('speed_limit', models.FloatField(default=50)),
                ('lanes_count', models.IntegerField(default=1)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('road_class', models.CharField(choices=[('motorway', '高速公路'), ('trunk', '快速路'), ('primary', '主干路'), ('secondary', '次干路'), ('tertiary', '支路'), ('residential', '居住区道路')], default='primary', max_length=20)),
                ('is_oneway', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '路段',
                'verbose_name_plural': '路段',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('srid', models.IntegerField(default=4326)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '路网',
                'verbose_name_plural': '路网',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_index', models.IntegerField()),
                ('lane_type', models.CharField(choices=[('through', '直行车道'), ('left_turn', '左转车道'), ('right_turn', '右转车道'), ('left_through', '左直合用车道'), ('right_through', '右直合用车道'), ('bus', '公交专用道'), ('emergency', '应急车道')], default='through', max_length=20)),
                ('width', models.FloatField(default=3.5)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('speed_limit', models.FloatField(blank=True, null=True)),
                ('is_parking', models.BooleanField(default=False)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='network.edge')),
            ],
            options={
                'verbose_name': '车道',
                'verbose_name_plural': '车道',
                'unique_together': {('edge', 'lane_index')},
            },
        ),
        migrations.AddField(
            model_name='edge',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='network.network'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('node_type', models.CharField(choices=[('intersection', '信号灯路口'), ('roundabout', '环岛')], max_length=20)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='network.network')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'unique_together': {('network', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection_type', models.CharField(choices=[('cross', '十字路口'), ('t_junction', 'T形路口'), ('y_junction', 'Y形路口'), ('multi_leg', '多路交叉')], default='cross', max_length=20)),
                ('channelization', models.JSONField(default=dict)),
                ('control_type', models.CharField(choices=[('signal', '信号控制'), ('stop', '停车控制'), ('yield', '让行控制')], default='signal', max_length=20)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intersection', to='network.node')),
            ],
            options={
                'verbose_name': '交叉口',
                'verbose_name_plural': '交叉口',
            },
        ),
        migrations.AddField(
            model_name='edge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='network.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='network.node'),
        ),
        migrations.CreateModel(
            name='Roundabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
                ('lanes_count', models.IntegerField(default=1)),
                ('inscribed_circle', models.FloatField(blank=True, null=True)),
                ('central_island', models.JSONField(default=dict)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roundabout', to='network.node')),
            ],
            options={
                'verbose_name': '环岛',
                'verbose_name_plural': '环岛',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(max_length=50)),
                ('cycle_length', models.FloatField()),
                ('offset', models.FloatField(default=0)),
                ('control_mode', models.CharField(choices=[('fixed', '固定配时'), ('actuated', '感应控制'), ('adaptive', '自适应控制')], default='fixed', max_length=20)),
                ('is_coordinated', models.BooleanField(default=False)),
                ('coordination_group', models.CharField(blank=True, max_length=50)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='network.node')),
            ],
            options={
                'verbose_name': '信号灯',
                'verbose_name_plural': '信号灯',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_index', models.IntegerField()),
                ('green_time', models.FloatField()),
                ('yellow_time', models.FloatField(default=3)),
                ('all_red_time', models.FloatField(default=1)),
                ('phase_type', models.CharField(choices=[('through', '直行相位'), ('left_turn', '左转相位'), ('pedestrian', '行人相位'), ('right_turn', '右转相位')], default='through', max_length=20)),
                ('allowed_movements', models.JSONField(default=list)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='network.signal')),
            ],
            options={
                'verbose_name': '相位',
                'verbose_name_plural': '相位',
                'unique_together': {('signal', 'phase_index')},
            },
        ),
        migrations.CreateModel(
            name='TrafficDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('demand_type', models.CharField(choices=[('od_matrix', 'OD矩阵'), ('turning_count', '转向流量'), ('link_flow', '路段流量')], max_length=20)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='network.network')),
            ],
            options={
                'verbose_name': '交通需求',
                'verbose_name_plural': '交通需求',
            },
        ),
        migrations.CreateModel(
            name='LaneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('straight', '直行'), ('left', '左转'), ('right', '右转'), ('u_turn', '掉头')], max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('has_yield', models.BooleanField(default=False)),
                ('from_lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='network.lane')),
                ('to_lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='network.lane')),
            ],
            options={
                'verbose_name': '车道连接',
                'verbose_name_plural': '车道连接',
                'unique_together': {('from_lane', 'to_lane')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('network', 'edge_id')},
        ),
        migrations.CreateModel(
            name='PhaseLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_right_of_way', models.BooleanField(default=True)),
                ('min_green_time', models.FloatField(default=7)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_lanes', to='network.lane')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_lanes', to='network.phase')),
            ],
            options={
                'verbose_name': '相位车道映射',
                'verbose_name_plural': '相位车道映射',
                'unique_together': {('phase', 'lane')},
            },
        ),
        migrations.CreateModel(
            name='ODMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FloatField()),
                ('vehicle_composition', models.JSONField(default=dict)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_origins', to='network.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_destinations', to='network.node')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_matrices', to='network.trafficdemand')),
            ],
            options={
                'verbose_name': 'OD矩阵',
                'verbose_name_plural': 'OD矩阵',
                'unique_together': {('demand', 'from_node', 'to_node')},
            },
        ),
    ]
