# Generated by Django 5.2.15 on 2026-06-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lane',
            name='signal_display',
            field=models.CharField(choices=[('arrow', '箭头灯'), ('round', '圆灯')], default='round', max_length=10),
        ),
        migrations.AddField(
            model_name='phase',
            name='light_type',
            field=models.CharField(choices=[('arrow', '箭头灯'), ('round', '圆灯'), ('mixed', '混合')], default='round', max_length=10),
        ),
        migrations.AddField(
            model_name='phase',
            name='permissive_movements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='phase',
            name='protected_movements',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='HistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sim_time', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('simulation', '仿真'), ('detector', '检测器'), ('import', '导入')], default='simulation', max_length=20)),
                ('vehicles', models.JSONField(default=list)),
                ('signals', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('intersection_metrics', models.JSONField(default=dict)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_snapshots', to='network.network')),
            ],
            options={
                'verbose_name': '历史快照',
                'verbose_name_plural': '历史快照',
                'indexes': [models.Index(fields=['network', 'timestamp'], name='network_his_network_47030b_idx')],
            },
        ),
    ]
