# Generated by Django 5.2.15 on 2026-06-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('idle', '空闲'), ('running', '运行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败')], default='idle', max_length=20)),
                ('duration', models.IntegerField(default=3600)),
                ('step_size', models.FloatField(default=1.0)),
                ('speed_multiplier', models.FloatField(default=1.0)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('current_time', models.FloatField(default=0)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('completed_vehicles', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='network.network')),
            ],
            options={
                'verbose_name': '仿真任务',
                'verbose_name_plural': '仿真任务',
            },
        ),
        migrations.CreateModel(
            name='SimulationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_delay', models.FloatField(default=0)),
                ('avg_queue_length', models.FloatField(default=0)),
                ('max_queue_length', models.IntegerField(default=0)),
                ('throughput', models.IntegerField(default=0)),
                ('avg_stops', models.FloatField(default=0)),
                ('intersection_metrics', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='simulation.simulation')),
            ],
            options={
                'verbose_name': '仿真指标',
                'verbose_name_plural': '仿真指标',
            },
        ),
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('vehicles', models.JSONField()),
                ('signals', models.JSONField()),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='simulation.simulation')),
            ],
            options={
                'verbose_name': '仿真快照',
                'verbose_name_plural': '仿真快照',
                'unique_together': {('simulation', 'time')},
            },
        ),
    ]
