# Generated by Django 5.2.15 on 2026-06-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationmetrics',
            name='vcr',
            field=models.FloatField(default=0),
        ),
    ]
